### ISSUE TITLE
Push to RubyGems.org

### ISSUE THREAD

**Issue by david942j** [sashs/ruby-keystone#1]
Hello,
We use keystone as dependency of [pwntools-ruby](https://github.com/peter50216/pwntools-ruby). Could you push keystone gem to RubyGems.org? Seems all gems on RubyGems.org can only have dependencies that also available on it.

Thanks a lot!

**Comment by sashs** [comment]
Hey, I will push that. As soon as I have time, I will do that.

**Comment by david942j** [comment]
Hi, any update?

**Comment by sashs** [comment]
Hi, sorry for the delay. I'm gonna push it today. But I have seen that there is another keystone gem. So I have to rename my gem. That also means that you have to change a little bit.

**Comment by sashs** [comment]
I renamed it to keystone_engine.
```
require 'keystone_engine'
require 'keystone_engine/<any>'
```
The module is renamed to KeystoneEngine
```
include KeystoneEngine
```
You can install it using this command:
```
gem install keystone-engine
```

**Comment by david942j** [comment]
Great! Thanks a lot ;)
